services:
  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - techchallengecontatos-network
    
    
  techchallengecontatos.web:
    image: techchallengecontatos.web
    build:
      context: .
      dockerfile: TechChallengeContatos.Web/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=postgres;Username=postgres;Password=test"
    depends_on:
      - postgres
    networks:
      - techchallengecontatos-network
      
  techchallengecontatos.consumerservice:
    image: techchallengecontatos.consumerservice
    build:
      context: .
      dockerfile: TechChallengeContatos.ConsumerService/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=postgres;Username=postgres;Password=test"
    depends_on:
      - postgres
    networks:
      - techchallengecontatos-network    
        
  rabbitmq:
     image: rabbitmq:3-management
     container_name: rabbitmq_management
     ports:
       - 5672:5672  
       - 15672:15672 
     environment:
       - RABBITMQ_DEFAULT_USER = admin
       - RABBITMQ_DEFAULT_PASS = tech123
     networks:
       - techchallengecontatos-network
     restart: always  
            
networks:
  techchallengecontatos-network:
    driver: bridge

