# Stage 1: Build the project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["TechChallengeContatos.Web/TechChallengeContatos.Web.csproj", "TechChallengeContatos.Web/"]
COPY ["TechChallengeContatos.Infra/TechChallengeContatos.Infra.csproj", "TechChallengeContatos.Infra/"]
COPY ["TechChallengeContatos.Domain/TechChallengeContatos.Domain.csproj", "TechChallengeContatos.Domain/"]
COPY ["TechChallengeContatos.Service/TechChallengeContatos.Service.csproj", "TechChallengeContatos.Service/"]
COPY ["TechChallengeContatosTest/TechChallengeContatosTest.csproj", "TechChallengeContatosTest/"]

RUN dotnet restore "TechChallengeContatos.Web/TechChallengeContatos.Web.csproj"

COPY . .

WORKDIR "/src/TechChallengeContatosTest"
RUN dotnet build "TechChallengeContatosTest.csproj" -c Release -o /app/build

# Stage 2: Run the tests
FROM build AS testrunner
WORKDIR /src/TechChallengeContatosTest

COPY --from=build /app/build /app/build
ENTRYPOINT ["dotnet", "test", "--logger:trx", "--results-directory", "/app/test-results"]
