version: '3.4'

services:
  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - techchallengecontatos-network
    
  techchallengecontatos.web:
    image: techchallengecontatos.web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=postgres;Username=postgres;Password=test"
    depends_on:
      - postgres
    networks:
      - techchallengecontatos-network

  techchallengecontatos.test:
    image: techchallengecontatos.test
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - postgres
    networks:
      - techchallengecontatos-network
    volumes:
      - ./test-results:/app/test-results # Montando o diretório de resultados dos testes no host

networks:
  techchallengecontatos-network:
    driver: bridge
